### PR TITLE
Add timestamp formatting for rosconsole

### PR DESCRIPTION
**Pull request by abrzozowski**
It's Cpp part of formatter Based on PR https://github.com/ros/ros_comm/pull/1458 from ros_comm. Related to the https://github.com/ros/ros_comm/pull/1533 for Python.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please retarget the current default branch `noetic-devel` and rebase your branch.

**Comment by abrzozowski** [comment]
I rebased my branch on top of `ros:melodic-devel`. Repository https://github.com/ros/rosconsole doesn't have a `noetic-devel` branch.

**Comment by abrzozowski** [comment]
@dirk-thomas Could you tell me, what should I do with this PR?

**Comment by dirk-thomas** [comment]
I just got around to create a `noetic-devel` branch, updated some indentation in e98e35d5b1425f1dd5e9cb4f27f170f8f00d696a and will go ahead merging this,

Thanks for the improvement.

**Comment by abrzozowski** [comment]
Added description in the ROS wiki: http://wiki.ros.org/action/diff/rosconsole?action=diff&rev1=74&rev2=75

**Comment by kakaday22** [comment]
Any possibility to have this enhancement done on Ros Melodic?

**Pull request merged**
