### PR TITLE
Support NO_COLOR environment variable

### PR DESCRIPTION
**Pull request by at-wat**
Prevent adding ANSI color when NO_COLOR is set.
Proposed at https://no-color.org/

ref: https://github.com/ros/rosconsole/pull/44

### CODE REVIEW

**Comment by at-wat** [comment]
@dirk-thomas please take a look when you have a chance.

**Comment by at-wat** [comment]
@dirk-thomas could you review this PR? Sorry for bothering you.

**Comment by at-wat** [comment]
@dirk-thomas @tfoote could anyone review this?

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Comment by dirk-thomas** [comment]
Cherry-picked to `melodic-devel` in a1c7060cab412f482e23f885905ec2c82fe0f4c1.

**Pull request merged**
